name: RetroFE Steam Deck Build (AppImage)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies for building AppImage
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          g++ \
          cmake \
          dos2unix \
          zlib1g-dev \
          libsdl2-2.0 \
          libsdl2-mixer-2.0 \
          libsdl2-image-2.0 \
          libsdl2-ttf-2.0 \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          gstreamer1.0-libav \
          zlib1g-dev \
          libglib2.0-0 \
          libglib2.0-dev \
          sqlite3

    # Download and install linuxdeploy
    - name: Install linuxdeploy
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        mv linuxdeploy-x86_64.AppImage /usr/local/bin/linuxdeploy

    # Build the project using CMake
    - name: Build with CMake
      run: |
        cmake RetroFE/Source -BRetroFE/Build
        cmake --build RetroFE/Build

    # Package the build as an AppImage
    - name: Create AppImage
      run: |
        # Set up the AppDir (AppImage directory structure)
        mkdir -p AppDir/usr/bin
        cp -r RetroFE/Build/* AppDir/usr/bin/

        # Run linuxdeploy to create the AppImage
        /usr/local/bin/linuxdeploy --appdir AppDir --output appimage --output-file RetroFE-SteamDeck.AppImage

    # Upload the AppImage to GitHub Releases
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: RetroFE Steam Deck Build - ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload AppImage Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: RetroFE-SteamDeck.AppImage
        asset_name: RetroFE-SteamDeck.AppImage
        asset_content_type: application/octet-stream
