name: RetroFE Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          g++ \
          cmake \
          dos2unix \
          zlib1g-dev \
          libsdl2-2.0 \
          libsdl2-mixer-2.0 \
          libsdl2-image-2.0 \
          libsdl2-ttf-2.0 \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libsdl2-ttf-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          gstreamer1.0-libav \
          zlib1g-dev \
          libglib2.0-0 \
          libglib2.0-dev \
          sqlite3

    # Configure the build
    - name: Configure CMake
      run: cmake RetroFE/Source -BRetroFE/Build

    # Build the project
    - name: Build
      run: cmake --build RetroFE/Build
