name: RetroFE AppImage Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            g++ \
            cmake \
            dos2unix \
            zlib1g-dev \
            libsdl2-2.0 \
            libsdl2-mixer-2.0 \
            libsdl2-image-2.0 \
            libsdl2-ttf-2.0 \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-good1.0-dev \
            gstreamer1.0-libav \
            zlib1g-dev \
            libglib2.0-0 \
            libglib2.0-dev \
            sqlite3
    
      - name: Configure
        run: |
          cmake RetroFE/Source -BRetroFE/Build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      - name: Build and Install
        run: |
          cmake --build RetroFE/Build --target install -- -j$(nproc) -- DESTDIR=$(pwd)/AppDir
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|aidenjbass|RetroFE|latest|*.AppImage.zsync`
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
